spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    username: root
    password: 20030303
    url: jdbc:mysql://localhost:3306/design
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        allow: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:project_documents/

sa-token:
  token-name: wind-electricity-token
  timeout: 196000 # 1小时
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.laityh.design

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  config: classpath:log4j2.xml